services:
  postgres:
    image: postgres:18-alpine
    container_name: dexchan_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dexchan_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-dexchan} -d ${POSTGRES_DB:-dexchan}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  dexchan:
    build: .
    container_name: dexchan
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DEXCHAN_TOKEN=${DEXCHAN_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
  dexchan_postgres_data:
