services:
  dexchan:
    build: .
    container_name: dexchan
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEXCHAN_TOKEN=${DEXCHAN_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - default
      - db_network

networks:
  db_network:
    external: true
    name: ${DB_NETWORK_NAME}
