name: Deploy dexchan (main)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Portainer Webhook
      run: curl -X POST -H "${{ secrets.PORTAINER_WEBHOOK_DEXCHAN }}"