name: Deploy dexchan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'

    - name: Install dependencies
      run: npm install

    - name: Set up SSH key
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        # Write the SSH private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        # Set the correct permissions for the key
        chmod 600 ~/.ssh/id_rsa
        # Add the server to known hosts
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        # List the keys in the SSH agent for debugging
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-add -l

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/ubuntu/dexchan_rework || exit
          git pull origin main
          npm install
          pm2 restart Dex-chan || pm2 start bot/index.js --name Dex-chan
        EOF
