name: Deploy dexchan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-add -l

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Source nvm script and set up environment
          export NVM_DIR="/home/ubuntu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

          # Verify npm and pm2 commands are available
          which npm
          npm -v
          which pm2
          pm2 -v

          # Navigate to the project directory and deploy
          cd /home/ubuntu/dexchan_rework || exit
          git pull origin main
          npm install
          pm2 restart dexchan_rework || pm2 start src/index.js --name dexchan_rework
        EOF