name: Deploy dexchan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'

    - name: Install dependencies
      run: npm install

    - name: Set up SSH agent
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
        # Add the SSH private key to the agent
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        # Ensure the .ssh directory exists
        mkdir -p ~/.ssh
        # Add the server to known hosts
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/ubuntu/dexchan_rework || exit
          git pull origin main
          npm install
          pm2 restart Dex-chan || pm2 start bot/index.js --name Dex-chan
        EOF
